#!/bin/sh

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <path_to_image>"
  exit 1
fi

IMAGE=$1

swww img "$IMAGE" --transition-type center --transition-duration 1 --transition-fps=144
matugen image "$IMAGE"
killall .waybar-wrapped
waybar > /dev/null 2>&1 &
killall .swaync-wrapped
swaync > /dev/null 2>&1 &
